
<section class="text">

	<p>Last updated April 10, 2020</p>

	<h2><strong>Coronavirusapi Terms and Conditions of Use Policy</strong></h2>
	<br>
	<ol type="A">
	  <li><h3><strong>Definitions</strong></h3></li>
	</ol>
	<p><strong>“Coronavirusapi”</strong> means Coronavirusapi, its parent, subsidiaries and affiliates.</p>
	<p><strong>“Coronavirusapi APIs”</strong> mean all software, including routines, data structures, object classes, protocols, programs, templates, libraries and interfaces, application programming interfaces (APIs), software development kits (SDKs), developer tools, technical documentation, Updates and other related materials, whether tangible or intangible, in whatever form or medium that are made available by Coronavirusapi at  <a href="https://coronavirusapi.com/" class="uri">https://coronavirusapi.com/</a> or as otherwise provided to you.</p>
	<p><strong>“Coronavirusapi Guides”</strong> mean all guides, materials, references and software, and other application or services provided by Coronavirusapi in association with the access and use of the Coronavirusapi APIs.</p>
	<p><strong>“Coronavirusapi API Services”</strong> include all protocols, Coronavirusapi APIs and Coronavirusapi Guides offered by Coronavirusapi.</p>
	<p><strong>“Application”</strong> or <strong>“App”</strong> means the software application, website, interface or any other means you use to access the Coronavirusapi API using the API Credentials, including a Private Application, Custom Application or a Public Application.</p>
	<p><strong>“API Client”</strong> means the unique Application configuration (including API Credentials) generated through the User Account.</p>
	<p><strong>“API Credentials”</strong> means the credentials that allow you to make authenticated requests to the Coronavirusapi API.</p>
	<p><strong>“Custom Application”</strong> means an Application that accesses the Coronavirusapi API via an API Client and is made available to a single User.</p>
	<p><strong>“User”</strong> means any individual or entity that visits or transacts via the coronavirusapi sites including affiliated sites and apps.</p>
	<p><strong>“Developer”</strong> means an individual or entity that develops, owns or operates one or more Application(s) that accesses or uses the Coronavirusapi API.</p>
	<p><strong>“Partner”</strong> means an individual or entity that has agreed to the terms of the Coronavirusapi Partner Program Agreement or other written agreement with Coronavirusapi relating to access to the Coronavirusapi API or participation in the Partner Program.</p>
	<p><strong>“Partner Account”</strong> means a Coronavirusapi Partner Program account.</p>
	<p><strong>“Partner Program”</strong> means the resources made available by Coronavirusapi to Partners. </p>
	<p><strong>“Public Application”</strong> means an Application that accesses the Coronavirusapi API via an API Client and that is made available to Users either via a URL or through the Coronavirusapi App Store, and that is not a Custom Application.</p>
	<p><strong>“Private Application”</strong> means an Application that accesses the Coronavirusapi API via Private API Credentials and is made available to a single User.</p>
	<p><strong>“API Terms”</strong> means Terms and Conditions for Coronavirusapi API Services.</p>
	<p><strong>“Terms”</strong> means the Terms and Conditions for use of this Website.</p>
	<p><strong>“Updates”</strong> means bug fixes, updates, upgrades, enhancements, modifications and new releases or versions of the Coronavirusapi API.</p>
	<ol start="2" type="A">
	  <li><h3><strong>Coronavirusapi API Services License and Terms </strong></h3></li>
	</ol>
	<p>Coronavirusapi owns the platform. By accessing or using the Coronavirusapi APIs, you agree to the Coronavirusapi API Services License and API Terms. You also agree to follow the Terms for use of this Website.</p>
	<h5><strong>General Access to Coronavirusapi API Services</strong></h5>
	<p>You must be of legal age to form a binding contract with Coronavirusapi to use the Coronavirusapi API Services. You shall not use the Coronavirusapi Services if you are not of legal age to form a binding contract with Coronavirusapi, you determine that you are unable to comply with these API Terms and Terms or you are prohibited by applicable law from accessing or using the Coronavirusapi API Services.</p>
	<h5><strong>Entity Access to Coronavirusapi API Services</strong></h5>
	<p>If you are accessing Coronavirusapi API Services on behalf of a company, entity, or organization (collectively “entity”), then you represent and warrant that you: (a) are an authorized representative of that entity with the authority to bind such entity to the Terms; (b) have read and understand the API Terms and Terms.</p>
	<h5><strong>Registration</strong></h5>
	<p>To access the Coronavirusapi API Services, you may be required to register and agree to applicable documentation we will provide. Your registration must be accurate and kept up-to-date by you at all times. Once you have successfully registered an Application, you will be given access credentials for your Application After an approved registration, you will be issued certain credentials, including but not limited to necessary security keys, secrets, tokens, and other credentials which may be required to access the Coronavirusapi APIs. You may not make credentials available to others including by embedding them in open source projects or assign them unless agreed to in writing, and only you may access the Coronavirusapi API Services with the credentials provided to you. You will not misrepresent or mask your identity or your credentials when accessing or using the Coronavirusapi API Services</p>

	<h5 id="open-source"><strong>Open Source</strong></h5>
	<p>To facilitate your Coronavirusapi API integration, Coronavirusapi may make certain Software Development Kit(s) (“SDK(s)”) and/or libraries available to you under a separate open source license. You agree that any Coronavirusapi API integration facilitated with such open source SDK(s) and/or libraries remains subject to the API Terms and Terms.</p>
	<h5><strong>Ownership</strong></h5>
	<p>Coronavirusapi owns all right, title and interest, including without limitation, all intellectual property rights and other rights in and to its software applications (including but not limited to the Coronavirusapi API Services and the Coronavirusapi Website), any intellectual property rights used in connection with the software applications, and other proprietary technology, including any data structures therein, accompanying documentation, and any updates or revisions to the foregoing. All rights not specifically conveyed are retained by Coronavirusapi.</p>
	<h5 id="licenses"><strong>Licenses</strong></h5>
	<p>Subject to your compliance with the Terms, Coronavirusapi hereby grants you a limited, revocable, non-exclusive, non-transferable, non-assignable license to access and use the Coronavirusapi API Services for sole purposes of developing, testing, using, and maintaining an integration of your application with the Coronavirusapi API Services. (the “License”)This License is for non-commercial use unless otherwise mutually agreed to by the parties in writing.</p>
	<p>Coronavirusapi may produce and distribute incidental depictions, including screenshots, video, or other content from your API client, and may use your entity or product name in the course of Coronavirusapi’s worldwide promotion, marketing, or demonstration of the Coronavirusapi API Services you are using; you hereby grant Coronavirusapi all necessary licenses, on a royalty-free basis, for these purposes.</p>
	<p>Subject to the rights granted to Coronavirusapi and limitations herein, you reserve and retain sole and exclusive ownership of all right, title, and interest in, to, and under (a) your extensions and applications, and (b) all modifications, corrections, repairs, translations, enhancements, and other derivative works and improvements of your extensions and applications, including all intellectual property rights arising therefrom or relating thereto (collectively, (a) and (b) are “Your Products”), to the extent Your Products do not infringe any of Coronavirusapi’s intellectual property rights. You are solely responsible for all costs incurred by you in the creation and maintenance of Your Products.</p>
	<h3 id="content"><strong>Content</strong></h3>
	<p>You are solely responsible for selecting all content made available through and contained in Your Products and for ensuring that such content complies with the API Terms and Terms and any other requirements applicable to such content. You are fully responsible for any information you provide to Coronavirusapi via the Coronavirusapi API Services.</p>
	<h5 id="feedback"><strong>Feedback</strong></h5>
	<p>If you provide feedback or suggestions about Coronavirusapi API Services, such information may be used for any purpose without obligation to you.</p>
	<h5 id="attribution"><strong>Attribution</strong></h5>
	<p>The documentation for the Coronavirusapi API you use may include guidelines for providing attribution to Coronavirusapi. You agree to provide any attribution in accordance with the guidelines and as further described in our Design Guidelines which may be updated from time to time. You can use these resources but you must not make any changes or modifications to them.</p>
	<h5 id="coronavirusapi-data"><strong>Coronavirusapi</strong> <strong>Data</strong></h5>
	<p>Except for third party content described in the <strong>Coronavirusapi Terms and Conditions of Use,</strong> “Coronavirusapi Data” includes all data received from Coronavirusapi through a Coronavirusapi API. Where such data includes non-public content relating to a user, such content must not be exposed to other users or to third parties without proper consent from that user.</p>
	<h5><strong>Termination</strong></h5>
	<p>These API Terms and Terms will apply for as long as you access and use the Coronavirusapi API Services. You may terminate these API Terms and Terms at any time by giving us notice and ceasing to access and use the Coronavirusapi API Services. Coronavirusapi may terminate these API Terms and Terms at any time, including if it determines that you have violated or attempted to violate the API Terms and Terms. These API Terms and Terms will terminate automatically in the event the Coronavirusapi APIs you use are no longer made available to you, if your Supplemental Agreement with Coronavirusapi is terminated or expires, or if any representations you make herein are deemed or found to be untrue.</p>
	<p>Upon termination of these API Terms and Terms, you will immediately stop using the Coronavirusapi APIs, cease all use of the Coronavirusapi intellectual property and delete any cached or stored content and any Coronavirusapi Data (including any Coronavirusapi Confidential Information). Coronavirusapi reserves the right to contact your end users to notify them of the termination of your right to use the Coronavirusapi APIs and the Coronavirusapi API Services.</p>
	<h5><strong>YOU MAY NOT Use the Coronavirusapi API Services to:</strong></h5>
	<ol type="a">
	  <li><p>disrupt, interfere with, or attempt to gain unauthorized access to services, servers, devices, or networks connected to or which can be accessed via the Coronavirusapi API Services;</p></li>
	  <li><p>migrate Customers away from a Coronavirusapi Offering, unless expressly permitted by Coronavirusapi pursuant to a duly executed written agreement;</p></li>
	  <li><p>Scrape, build databases or otherwise create copies of any data accessed or obtained using the Coronavirusapi API Services except as necessary to enable an intended usage scenario for your Application;</p></li>
	  <li><p>Request from the Coronavirusapi API Services more than the minimum amount of data, or more than the minimum data permissions that your Application needs for the intended functionality of your Application;</p></li>
	  <li><p>Use an unreasonable amount of bandwidth, or adversely impact the stability of the Coronavirusapi API Services or the behavior of other apps using the Coronavirusapi API Services;</p></li>
	  <li><p>Attempt to circumvent the limitations Coronavirusapi sets on your use of the Coronavirusapi API Services-for example., limiting the number of Coronavirusapi API Services requests that you may make or the number of users you may serve or other limits imposed in its sole discretion;</p></li>
	  <li><p>work around any technical limitations of the Coronavirusapi API Services or reverse engineer, decompile or disassemble the Coronavirusapi API Services, except and only to the extent that applicable law expressly permits, despite this limitation;</p></li>
	  <li><p>identify, exploit or publicly disclose any potential security vulnerabilities;</p></li>
	  <li><p>request, use or make available any data outside any permissions expressly granted by Customers in connection with using your Application;</p></li>
	  <li><p>Use or transfer any data accessed or obtained including any data aggregated, anonymized or derived from that data for advertising or marketing purposes including (i) targeting ads, or (ii) serving ads. For purposes of clarity, this prohibition on using Coronavirusapi API Services Data for advertising or marketing purposes does not extend to using other data, such as (i) the number of users of your Application, (ii) a user identifier you independently receive from a user (e.g., an email address you receive when a user enrolls to use your Application, a device identifier, or an advertising identifier), or (iii) a product or service identifier that identifies a Coronavirusapi Offering;</p></li>
	  <li><p>Make your Application available for use in a manner that circumvents the need for users to obtain a valid license if any to the Coronavirusapi API Services;</p></li>
	  <li><p>Redistribute or resell, or sublicense access to any data accessed through the Coronavirusapi API Services; or</p></li>
	  <li><p>Misrepresent expressly, by omission, or implication, the need for users to obtain a valid license to the Coronavirusapi application or service if any that is accessed through the Coronavirusapi API Services;</p></li>
	  <li><p>falsify or alter any unique referral identifier in, or assigned to an Application, or otherwise obscure or alter the source of queries coming from an Application to hide a violation of this agreement; or</p></li>
	  <li><p>Use the Coronavirusapi API Services in a way that could create, in Coronavirusapi's sole discretion and judgment, an unreasonable risk to Customers from a security or privacy perspective.</p></li>
	</ol>
	<h5><strong>Security</strong></h5>
	<p>You warrant that your Application has been developed to operate with Coronavirusapi API Services content in a secure manner. Your network, operating system and the software of your servers, databases, and computer systems (collectively, &quot;<strong>Systems</strong>&quot;) must be properly configured to securely operate your Application and store content collected through your Application (including the Coronavirusapi API Services content). Your Application must use reasonable security measures to protect the private data of your users.</p>
	<p>We may use technology to detect, prevent or limit the impact of any issues caused by your Application (before, after, or instead of suspension of your access). This may include, for example, (i) filtering to stop spam, (ii) performing security or privacy monitoring regarding scraping, denial of service attacks, user impersonation, application impersonation, or illicit consent grant(s), or (iii) limiting or terminating your access to the Coronavirusapi API Services.</p>
	<h5><strong>Audit</strong></h5>
	<ol type="a">
	  <li><p>You will permit Coronavirusapi reasonable access to your Application for purposes of monitoring compliance with these Terms. You will respond to any questions by Coronavirusapi about your compliance with these Terms.</p></li>
	  <li><p>Without limiting the foregoing, upon request by Coronavirusapi, you will provide us (or an independent auditor acting on our behalf) with up to two full-feature client account-level instances to access your Application (and/or other materials relating to your use of the API) as reasonably requested by us to verify your compliance with these API Terms and Terms (including, in particular, your security and privacy obligations under these API Terms and Terms).</p></li>
	  <li><p>We may restrict or terminate access to the Coronavirusapi API Services or perform an audit (including by hiring an independent auditor acting on our behalf) of your Application if you fail to provide adequate information and materials (including up to two full-featured instances of your Application) to verify your compliance with these API Terms and Terms.</p></li>
	  <li><p>You must have a process to respond to any vulnerabilities in your Application, and in the case of any vulnerabilities related to your Application's connection to the Coronavirusapi API Services discovered by you or reported to you by a third party, you agree that you will timely provide vulnerability details to the Coronavirusapi.</p></li>
	</ol>
	<blockquote>
	  <h5><strong>Data Breach</strong></h5>
	  <p>In the event of a data breach by you resulting from any aspect of the Coronavirusapi API Services involving your Application or any data collected through your Application, you will promptly contact Coronavirusapi and provide details of the data breach. You agree to refrain from making public statements (e.g., press, blogs, social media, bulletin boards, etc.) without prior written and express permission from Coronavirusapi in each instance as it relates to the Coronavirusapi API Services.</p>
	</blockquote>
	<p>The rights and requirements of this <strong>Security</strong> section will survive for five (5) years following any termination of these Coronavirusapi API Services.</p>
	<h5><strong>Support</strong></h5>
	<p>Because the Coronavirusapi API Services are provided &quot;as is,&quot; we may not provide support services for them. You are solely responsible for the quality of your Application and providing support for your Application.</p>
	<h5><strong>Compliance with Applicable Privacy and Data Protection Laws when using the Coronavirusapi API Services</strong></h5>
	<p>You must comply with all laws and regulations applicable to your use of the data accessed through the Coronavirusapi API Services, including without limitation laws related to privacy, biometric data, data protection and confidentiality of communications. Your use of the Coronavirusapi API Services is conditioned upon implementing and maintaining appropriate protections and measures for your service and Application, and that includes your responsibility to the data obtained through the use of the Coronavirusapi API Services. For the data you obtained through the Coronavirusapi API Services, you must:</p>
	<ol type="a">
	  <li><p>obtain all necessary consents before processing data and obtain additional consent if the processing changes (&quot;<strong>Data Access Consents</strong>&quot;),</p></li>
	  <li><p>In the event you're storing data locally, ensure that data is kept up to date and implement corrections, restrictions to data, or the deletion of data as reflected in the data obtained through your use of the Coronavirusapi API Services,</p></li>
	  <li><p>implement proper retention and deletion policies, including deleting all data when your user abandons your Application, uninstalls your Application, closes its account with you, or abandons the account,</p></li>
	  <li><p>maintain and comply with a written statement available to Customers and users that describes your privacy practices regarding data and information you collect and use (&quot;<strong>Your Privacy Statement</strong>&quot;), and that statement must be as protective as the Coronavirusapi Privacy Statement, and</p></li>
	  <li><p>Nothing in the Agreement shall be construed as creating a joint controller or processor-subprocessor relationship between you and Coronavirusapi.</p></li>
	</ol>
	<h5><strong>Changes to the Coronavirusapi API Services and Terms</strong></h5>
	<p><strong>WE MAY CHANGE OR DISCONTINUE THE AVAILABILITY OF SOME OR ALL OF THE CORONAVIRUSAPI API SERVICES AND API TERMS AND TERMS</strong> <strong>AT ANY TIME FOR ANY REASON WITH OR WITHOUT NOTICE.</strong> Such changes may include, without limitation, removing or limiting access to specific API(s), requiring fees or setting and enforcing limits on your use of additions to the Coronavirusapi API Services. We may also impose limits on certain features and services or restrict your access to some or all of the Coronavirusapi API Services. We may release subsequent versions of the Coronavirusapi API Services and require that you use those subsequent versions, at your sole cost and expense.</p>
	<p>Any version of the Coronavirusapi API Services designated as Preview, may not work in the same way as a final version. We may change or not release a final or commercial version of a Preview API in our sole discretion.</p>
	<h5><strong>WE MAY MODIFY THESE API TERMS AND TERMS AT ANY TIME, WITH OR WITHOUT PRIOR NOTICE TO YOU. YOUR CONTINUED USE OF THE CORONAVIRUSAPI API SERVICES FOLLOWING THE RELEASE OF A SUBSEQUENT VERSION OF THESE API TERMS AND TERMS WILL BE DEEMED YOUR ACCEPTANCE OF ANY MODIFICATIONS TO THESE API TERMS AND TERMS.</strong></h5>
	<h5><strong>Termination</strong></h5>
	<ol type="a">
	  <li><p>We may suspend or immediately terminate these API Terms and Terms, any rights granted herein, and/or your license to the Coronavirusapi API Services, in our sole discretion at any time, for any reason. You may terminate these API Terms and Terms at any time by ceasing your access to the Coronavirusapi API Services</p></li>
	  <li><p>Upon termination, all licenses granted herein immediately expire and you must cease use of the Coronavirusapi API Services. You must also comply with Customer's instruction to return or delete any data accessed or obtained through the Coronavirusapi API Services. Neither party will be liable to the other for any damages resulting solely from termination of these API Terms and Terms.</p></li>
	</ol>
	<ol start="3" type="A">
	  <li><h3><strong>Website Terms and Conditions</strong></h3></li>
	</ol>
	<h5><strong>Agreement to Terms and Conditions</strong></h5>
	<p>PLEASE READ THE FOLLOWING TERMS AND CONDITIONS (“TERMS”) CAREFULLY. THEY GOVERN YOUR ACCESS AND USE OF THE CORONAVIRUSAPI WEBSITE (“WEBSITE”) AND ADDITIONALLY CORONAVIRUSAPI API SERVICES. BY ACCESSING THIS WEBSITE, YOU ACKNOWLDGE AND AGREE THAT YOU HAVE READ, UNDERSTAND AND WILL BE BOUND BY THESE TERMS.  IF YOU ARE NOT WILLING TO BE BOUND BY EACH AND EVERY TERM, YOU MAY NOT USE, AND MUST CEASE USING, THE WEBSITE.</p>
	<h5><strong>Materials</strong></h5>
	<p>The materials on this Website include, but are not limited to, all content and materials, including designs, images, editorial, text, graphics, audiovisual materials, multimedia elements, photographs, videos, music, sound recordings, reports, white papers, blogs, case studies, press releases, press stories, documents, software, information, patterns, data, dashboards, related tools, and other products or services, the appearance of this Website itself, and any other work” (Collectively, the “Content or Materials”), and are provided by Coronavirusapi for informational purposes only and are not legal or business advice. By accessing or using this Website, you agree to be bound by the general Terms including Coronavirusapi’s Privacy Policy which is made a part of and incorporated by reference into these Terms.</p>
	<h5><strong>Revisions</strong></h5>
	<p>Coronavirusapi has the right to revise these Terms at any time without notice to you by updating these Terms. The Website is made available on an “as is” basis with no representation or warranty with respect to the functionality or availability and with no guarantee that they are complete, accurate, or timely, nor any guaranty of results from their use. Coronavirusapi has no obligation to update the Content, except as required to do so under applicable law. Coronavirusapi reserves the right to change, suspend, or discontinue any aspects of, the Content or Website at any time without prior notice to you.</p>
	<h5><strong>Access</strong></h5>
	<p>Access may be suspended at any time without notice. You are responsible for regularly reviewing these Terms. Your continued use of this Website following any changes to the Terms shall constitute your acknowledgment and acceptance of such changes. You may terminate these Terms by not using or discontinuing use of the Website if you do not agree with any such changes. Use of the Website will constitute your acknowledgment and signature to these Terms and evidence that you have read, understand, accept, and agree to the terms of the Agreement. You may print a copy of these Terms for your records.</p>
	<h5><strong>User Generated Content including Community Pages</strong></h5>
	<p>The Website may contain functionality that permits you to comment on articles; share materials; provide ideas, proposals, suggestions, user generated content, or otherwise make available certain materials through or in connection with your use of the Website(s) (collectively, “User Generated Content” or “Submission(s)”).Whether related to the Website(s) or otherwise, you acknowledge and agree that your Submissions are not confidential; that your provision of Submissions is gratuitous, unsolicited and without restriction; and that the provision of any Submission does not place Coronavirusapi under any fiduciary or other obligation or liability. Coronavirusapi may (but has no obligation to) monitor, evaluate, alter or remove Submissions before or after they appear on the site; however, we have no control over and are not responsible for any use or misuse (including any distribution) by any third party of Submissions.</p>
	<h5><strong>Community Areas</strong></h5>
	<p>Certain areas of the Website that permit you to submit User Generated Content may include, but are not limited to, chat rooms and message boards (collectively, “Community Areas”). You acknowledge and understand that when using Community Areas you will be exposed to other users’ User Generated Content. Coronavirusapi is not responsible for the accuracy, usefulness, timeliness, accuracy, efficacy, veracity, or safety of such other users’ User Generated Content. You further understand and acknowledge that you may be exposed to other users’ User Generated Content that are inaccurate, offensive, indecent, or objectionable. Coronavirusapi assumes no responsibility for actively monitoring Community Areas for inappropriate User Generated Content. Coronavirusapi reserves the right to remove or edit User Generated Content at any time and for any reason. If at any time Coronavirusapi chooses, in its sole discretion, to monitor Community Areas or edit User Generated Content, Coronavirusapi nonetheless assumes no responsibility or liability for the User Generated Content, no obligation to modify or remove any inappropriate User Generated Content, and no responsibility or liability for the conduct of any user submitting User Generated Content.</p>
	<h5><strong>User Generated Content Rules</strong></h5>
	<p>You agree to comply with the User Generated Content Rules and shall not upload, post, or publish any User Generated Content to the Website or Community Areas:</p>
	<ol type="a">
	  <li><p>that is known by you to be false, inaccurate, or misleading;</p></li>
	  <li><p>that infringes any third party’s copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy;</p></li>
	  <li><p>that violates any law, statute, ordinance, or regulation (including, but not limited to, those governing export control, consumer protection, unfair competition, anti-discrimination, false advertising, the exploitation of minors , gambling, and piracy);</p></li>
	  <li><p>that is or may reasonably be considered to be defamatory, libelous, hateful, racially, sexual and/or pornographic in nature or religiously biased or offensive, unlawfully threatening or unlawfully harassing to any individual, partnership, or corporation;</p></li>
	  <li><p>for which you were compensated or granted any consideration by any third party;</p></li>
	  <li><p>that includes any information that references other website(s), addresses, email addresses, contact information or phone numbers; or that contains any computer viruses, worms or other potentially damaging computer programs or files;</p></li>
	  <li><p>that is off-topic or irrelevant material to any Community Area;</p></li>
	  <li><p>that is unsolicited or unauthorized advertising, promotional materials, or any other form of solicitation, without our express written approval; or</p></li>
	  <li><p>that attempts to impersonate any person or entity or falsely state or otherwise misrepresent your professional or other affiliation with any person or entity or indicate that you are an employee or representative of Coronavirusapi.</p></li>
	</ol>
	<h5><strong>User Generated Content – License</strong></h5>
	<p>You warrant that you are the author and owner of the intellectual property rights in your User Generated Content. You automatically grant Coronavirusapi a worldwide, perpetual, irrevocable, royalty-free, non-exclusive, transferable and fully sublicensable right and license to use, publish, reproduce, display, modify and otherwise use, adapt, sell and distribute, delete in its entirety, translate, create derivative works from, publicly perform, analyze, and incorporate your User Generated Content into any form, medium or technology, without compensation to you for any purpose including promotional purposes such as testimonials.</p>
	<h5><strong>Caching</strong></h5>
	<p>You acknowledge and agree that your Submissions may be subject to caching due to technical processing and transmission of the Website.</p>
	<h5><strong>Waiver of Moral Rights</strong></h5>
	<p>You waive and relinquish any moral rights that may exist in your User Generated Content, and agree not to assert any moral rights in your User Generated Content. Coronavirusapi does not want, and cannot accept, any User Generated Content you consider to be confidential or proprietary. Accordingly, all User Generated Content is not confidential and will become and remain Coronavirusapi’s property, subject to the Terms and Privacy Policy.</p>
	<h5><strong>Usernames and Passwords</strong></h5>
	<p>If, as part of the registration process for access to portions of the Community Areas, you are asked to select a username and password, then you will be responsible for all activities occurring under your username and for keeping your password secure. You are solely responsible for any and all uses of your username, password, and account. You shall immediately notify Coronavirusapi of any unauthorized use of your account or any suspected loss or disclosure of your username and password. Coronavirusapi shall have no liability for any damage or loss that you incur as a result of someone else using your password or account, either with or without your knowledge.</p>
	<h5><strong>Age of Majority</strong></h5>
	<p>If you are an individual, you represent and warrant that you have reached the age of majority in the jurisdiction in which you reside, and that you are in any event at least 18 years old. You agree that you will not use this Website if you are under the age of 18.</p>
	<h5><strong>Organization Access</strong></h5>
	<p>If you are using the Website(s) on behalf of a corporation or other organization, you represent and warrant that you have the ability to agree to these Terms on behalf of such organization and all references to &quot;you&quot; throughout these Terms will include such organization, jointly and severally with you personally.</p>
	<h5><strong>If you choose to make publicly available any of your personally identifiable or other information through the Website (for example through posting a comment or other form of Submission), you do so at your own risk and you agree that such Submissions by you will comply with all relevant requirements set out in these Terms.</strong></h5>
	<h5><strong>General Use</strong></h5>
	<p>Except as expressly provided herein, you may not use, download, upload, copy, print, display, perform, reproduce, publish, license, post, create derivative works from, transmit, or distribute any Content from this Website in whole or in part without the express prior written permission of Coronavirusapi. Any unauthorized use of any Content, Materials or this Website may violate copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes. Coronavirusapi expressly disclaims liability from any unauthorized use of any Content, Materials or this Website, Any rights not expressly granted herein are reserved by Coronavirusapi. You may not “mirror” any Content without Coronavirusapi’s prior express written permission. Unless expressly authorized, you further agree (1) to not copy, modify, deep link, rent, lease, loan, sell, assign, sublicense, grant a security interest in or otherwise transfer any right or interest in the Content or Materials; (2) remove any proprietary notice or label on the Content or Materials; or (2) allow any third party to engage in the foregoing.</p>
	<h5><strong>Intellectual Property</strong></h5>
	<p>All Content, Materials, copyright, trademark, trade dress, or other intellectual property owned, controlled, or licensed by Coronavirusapi, are the property of their respective owners, and are protected by U.S. and international intellectual property laws and conventions, including but not limited to copyright. Except where expressly stated otherwise, all source code, processes, designs, technologies, URLs, domain names, marks, logos forming our Website (collectively “Website Materials”) are fully vested in us, our licensors, or our suppliers and are protected by applicable copyrights, trademarks, patents, trade secret, or other proprietary rights and laws. You agree that the Content and Materials are licensed subject to these Terms, including the disclaimers and limitations of liability herein. Nothing in your use of the Website or these Terms grants you any right, title or interest in or to the Content or Materials except the limited right to use the Website as set out in these Terms for non-commercial use unless otherwise mutually agreed to in writing.</p>
	<h5><strong>Indemnity Arising from Submissions</strong></h5>
	<p>You will indemnify and hold harmless from any liabilities, proceedings, actions, claims, causes of action, demands, debts, losses, damages, charges, costs, and expenses including reasonable legal costs, any amount to satisfy or pay a judgment and expenses related to or arising from your Submission including instances where your Submission may infringe on Third Party Content or other third party IP rights or is inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful. You will indemnify</p>
	<h5><strong>Trademark</strong></h5>
	<p>The Coronavirusapi logo is a trademark of Coronavirusapi, which may be registered in the United State and other countries. Other Coronavirusapi product or service names or logos referenced in this Website are trademarks or may be registered trademarks of Coronavirusapi. All other products, services, and company names mentioned in the Website may be trademarks of their respective owners. Not all of the logos, trademarks or tradenames of Coronavirusapi are used on this Website, nor all of those logos, trademarks, or tradenames licensed to Coronavirusapi by third parties. The absence of a product or service name or logo from this list does not constitute a waiver of the trademark or other intellectual property rights of Coronavirusapi concerning that name or logo. You may not use any trademark displayed on the Website or Content without the express prior written permission of Coronavirusapi or the relevant owner of the trademark.</p>
	<h5><strong>Website Links</strong></h5>
	<p>This Website may contain links to other website(s) controlled by parties other than Coronavirusapi. Coronavirusapi has no control over any such other website(s), the contents therein or the products/services offered. The existence of any such links shall not constitute an endorsement, representation or warranty by Coronavirusapi of such website(s), their contents, nor the products or services offered therein. Third Party Content may be subject to applicable copyright, trademark, patent, trade secret, or other proprietary rights and laws. Creating or maintaining any link from another website to this Website is prohibited. Running or displaying this Website or any Content in frames or through similar means on another website is prohibited.</p>
	<h5><strong>Termination</strong></h5>
	<p>Coronavirusapi may terminate these Terms and your access to and use of the Website, or any portion thereof, immediately, in its sole discretion, at any time without cause. You may also terminate your own use of the Website by not using the Website. Upon the termination of your use of this Website, whether termination is by Coronavirusapi or according to your own discretion, you must promptly remove, delete, or destroy, all Content downloaded or otherwise obtained from the Website, as well as all copies of such materials, whether made under the terms of these Terms or otherwise. You agree that if you delete the account to which your Submissions are connected, you acknowledge and agree that Coronavirusapi may retain a copy or copies of same for archival, compliance and other business purposes, subject to your license to us and our Privacy Policy.</p>
	<h5><strong>General Indemnity</strong></h5>
	<p>You shall defend, indemnify, and hold harmless, Coronavirusapi, its affiliates, subsidiaries suppliers, licensors, providers, officers, directors, agents and employees from and against any and all claims, liabilities, damages, losses, or expenses, including reasonable attorneys’ fees and costs, arising out of or in any way related with your access to, or use of, the Website or the Content, your breach of any provision of these Terms, or User Generated Content. Coronavirusapi reserves the right, in its sole discretion and at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you or users of your account under this section. You will cooperate as fully as reasonably required in the defense of any such claim.</p>
	<h5><strong>Website Feedback</strong></h5>
	<p>Coronavirusapi welcomes your comments and feedback regarding this Website and your Submissions as defined above. However, Coronavirusapi does not want, and cannot accept, any ideas, materials, or suggestions, you consider to be confidential or proprietary. Accordingly, all comments, feedback, ideas, suggestions and other similar Submissions disclosed, submitted, or offered to us using this Website or otherwise are not confidential and will become and remain our property.</p>
	<h5><strong>LIABILITY, WARRANTIES, AND DISCLAIMERS </strong></h5>
	<h5><strong>Disclaimer</strong></h5>
	<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CORONAVIRUSAPI DISCLAIMS ALL LIABILITY AND SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOST PROFITS OR REVENUES, GOODWILL, WORK STOPPAGE, SECURITY BREACHES, VIRUSES, COMPUTER FAILURE OR MALFUNCTION, USE, DATA OR OTHER INTANGIBLE LOSSES OR COMMERCIAL DAMAGES, EVEN IF ANY OF SUCH PARTIES ARE ADVISED OF THE POSSIBILITY OF SUCH LOSSES, ARISING UNDER OR IN CONNECTION WITH THESE TERMS, THE SITE, THE USE OF OR INABILITY TO USE THE SAME, OR ANY OTHER SUBJECT MATTER HEREOF.</p>
	<h5><strong>Explicit Disclaimer of Third Party Privacy Policies</strong></h5>
	<p>Coronavirusapi explicitly disclaims responsibility for the privacy policies and customer information practices of third-party website(s) linked to this Website.</p>
	<h5><strong>“As Is” Basis</strong></h5>
	<p>Coronavirusapi cannot guarantee that the Content will be accurate or up-to-date. From time to time, Coronavirusapi may make suggestions or recommendations of certain products or services, however, Coronavirusapi make no guarantee as to satisfaction for our suggestions or recommendations or that the suggested or recommended products or services will meet your expectations. EXCEPT TO THE EXTENT EXPRESSLY PROVIDED OTHERWISE BY CORONAVIRUSAPI IN THESE TERMS OR TO THE EXTENT THAT THESE DISCLAIMERS ARE HELD TO BE LEGALLY INVALID, THE WEBSITE AND THE CONTENTS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. CORONAVIRUSAPI EXPLLICITLY DISCLAIMS AND SHALL NOT BE RESPONSIBLE OR LIABLE TO YOU OR ANY OTHER PERSON FOR ANY ERRORS OR OMISSIONS IN THE WEBSITE(S); ANY INFORMATION MADE AVAILABLE THROUGH THEM; ANY DECISION MADE OR ACTION TAKEN IN RELIANCE ON THE WEBSITE(S) OR THE INFORMATION MADE AVAILABLE THROUGH THEM; OR FOR ANY LOSS OR DAMAGES - INCLUDING CONSEQUENTIAL, SPECIAL OR SIMILAR DAMAGES - THAT ARISE OUT OF OR IN CONNECTION WITH YOUR USE OF THE WEBSITE(S) OR ANY INFORMATION OR MATERIALS OBTAINED BY YOU VIA OR IN CONNECTION WITH THE WEBSITE(S).CORONAVIRUSAPI HEREBY DISCLAIMS ALL EXPRESS AND IMPLIED REPRESENTATIONS, WARRANTIES, GUARANTIES, AND CONDITIONS, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ACCURACY. CORONAVIRUSAPI MAKES NO REPRESENTATIONS, WARRANTIES, GUARANTIES, OR CONDITIONS AS TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY, OR COMPLETENESS OF ANY OF THIS WEBSITE OR THE CONTENT. USE OF THE WEBSITE AND THE CONTENT IS AT YOUR SOLE RISK.</p>
	<p>Some jurisdictions prohibit the disclaimer of certain warranties or conditions or the limitation of certain types of liability. In such circumstances, to the extent that such prohibitions prohibit any exclusions and limitations in these Terms, such exclusions and limitations will not apply to you strictly to the extent necessary to make these Terms consistent with such prohibitions.</p>
	<h5><strong>Limitation of Liability</strong></h5>
	<p>NEITHER CORONAVIRUSAPI NOR ITS SUPPLIERS, LICENSORS, PROVIDERS, OFFICERS, DIRECTORS, PRINCIPALS, PARTNERS, AGENTS, OR EMPLOYEES, (COLLECTIVELY THE “EXCLUDED PARTIES”) SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES, WHETHER IN CONTRACT, TORT, OR OTHERWISE, ARISING OUT OF OR RELATING TO THESE TERMS OR RESULTING FROM THE USE OF OR THE INABILITY TO USE THE WEBSITE OR THE CONTENT, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, USE, DATA, OR OTHER INTANGIBLE DAMAGES, EVEN IF SUCH EXCLUDED PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF, OR OTHERWISE COULD HAVE FORESEEN, SUCH DAMAGES.</p>
	<h5><strong>Network Disruption</strong></h5>
	<p>You acknowledge and accept that use of the Website(s) is subject to the risks inherent in any connection and transmission on the internet, in particular in relation to security risks and vulnerabilities, technical performance and risk of interruption. Accordingly, neither Coronavirusapi nor any Coronavirusapi Parties are liable to you in any circumstances for any losses or damages caused by disruption or failure of internet networks or for any interruptions to or restrictions on the accessibility of the Website(s) arising for any reason, including, but not limited to, by reason of a virus, security related vulnerability, or technical or operational failure of any nature.</p>
	<h5><strong>User Conduct</strong></h5>
	<h5><strong>Acceptable Conduct</strong></h5>
	<p>You will use the Website only for lawful purposes.  If at any time you become aware of any violation, by any person or entity, of any part of these Terms, you will immediately notify us by contacting <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a> and provide us with assistance, as requested, to stop or remedy such violation.</p>
	<h5><strong>Location</strong></h5>
	<p>You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. If any applicable law, rule or regulation prohibits you to access the Website(s), you may not access them.  If you nevertheless access or use the Website(s), you will still be bound to these Terms and shall have all the obligations, responsibilities and liabilities as if you were eligible to do so.</p>
	<h5><strong>Prohibited conduct</strong></h5>
	<p>In using the Website(s), you must not do any of the following:</p>
	<ol type="a">
	  <li><p>Post, transmit or otherwise make available through the Website any materials that are or may be: (a) threatening, harassing, degrading, hateful or intimidating, or otherwise fail to respect the rights and dignity of others; (b) defamatory, libelous, fraudulent or otherwise tortious; (c) obscene, indecent, pornographic or otherwise objectionable; or (d) a virus, worm, Trojan horse, Easter egg, time bomb, spyware or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software or equipment (each, a “Virus”).</p></li>
	  <li><p>Post, transmit, or otherwise make available through the Website(s) any material protected by copyright, trademark, trade secret, right of publicity or privacy or any other proprietary right, without the express prior written consent of the applicable owner.</p></li>
	  <li><p>Use the Website(s) for any commercial purpose or otherwise use the Website(s) for processing data or other information on behalf of any third party.</p></li>
	  <li><p>Use the Website(s) for any purpose that is fraudulent or otherwise tortious or unlawful.</p></li>
	  <li><p>Interfere with or disrupt the operation of the Website(s) or the servers or networks used to make the Website(s) available, including by hacking or defacing any portion of any of the Website(s); or violate any requirement, procedure or policy of such servers or networks.</p></li>
	  <li><p>Restrict or inhibit any other person from using the Website(s).</p></li>
	  <li><p>Create or share content without first obtaining any necessary permissions from third parties or otherwise use the Website(s) to post or transmit any information that you do not have the right to provide; that would violate any applicable law or regulation; or that would violate, infringe or misappropriate any third party right or interest.</p></li>
	  <li><p>Reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, timeshare, distribute or otherwise exploit any portion of (or any use of) the Website(s) except as expressly authorized herein, without Coronavirusapi’s express prior written consent.</p></li>
	  <li><p>Reverse engineer, decompile or disassemble any portion of any of the Website(s), except where such restriction is expressly prohibited by applicable law.</p></li>
	  <li><p>Remove or alter any copyright, trademark or other proprietary rights notice on the Website(s) or content you access via the Website(s).</p></li>
	  <li><p>Frame or mirror any portion of the Website(s), or otherwise incorporate any portion of the Website(s) into any product or service, without Coronavirusapi’s express prior written consent.</p></li>
	  <li><p>Systematically download and store Website(s)’ content.</p></li>
	  <li><p>Use any robot, spider, Website(s) search/retrieval application or other manual or automatic device to (a) retrieve, index, “scrape,” “data mine” or otherwise gather content from the Website(s), (b) reproduce or circumvent the navigational structure or presentation of the Website(s), or (c) harvest or collect information about users of the Website(s) without Coronavirusapi’s express prior written consent.</p></li>
	</ol>
	<h5><strong>If you do not comply with these Terms (or if we have reasonable grounds to suspect or are investigating suspected non-compliance), we may suspend your access to the Website(s) or take any other steps we consider appropriate.</strong></h5>
	<h5><strong>Privacy and Personal Information</strong></h5>
	<p>To learn about how Coronavirusapi protects your privacy, please refer to Coronavirusapi’s Privacy Policy. Coronavirusapi’s Privacy Policy is incorporated herein by reference and is made part of these Terms.</p>
	<h5><strong>DMCA</strong></h5>
	<p>Coronavirusapi takes claims of copyright infringement seriously. The Digital Millennium Copyright Act of 1998 (the “DMCA”) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that materials available on the Website(s) infringe your copyright, you (or your agent) may send to Coronavirusapi a written notice by mail or e-mail, requesting that Coronavirusapi remove such material or block access to it. If you believe in good faith that someone has wrongly filed a notice of copyright infringement against you, the DMCA permits you to send to Coronavirusapi a counter-notice. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA. See<a href="http://www.copyright.gov/"><strong> http://www.copyright.gov/</strong></a> for details. Coronavirusapi will promptly investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act, Title 17, United States Code, Section 512(c)(2). Notifications of claimed copyright infringement should be sent to the designated agent, <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a>. We suggest that you consult your legal advisor before filing a DMCA notice or counter-notice.</p>
	<h5><strong>Compliance with Law</strong></h5>
	<p>You agree to comply with all applicable laws, statutes, ordinances and regulations regarding your use of this Website. You acknowledge and agree that violations of these Terms could subject you to criminal or civil penalties.</p>
	<h5><strong>Miscellaneous</strong></h5>
	<h5><strong>Jurisdiction</strong></h5>
	<p>These API Terms and Terms will be governed by and interpreted in accordance with the laws of the State of New York, U.S.A., excluding its conflicts of law principles. Any controversy or claim arising out of or relating to these API Terms and Terms or the existence, validity, breach or termination thereof, whether during or after its term, will be brought in the federal or state courts having jurisdiction over Westchester County, New York, to whose exclusive jurisdiction you hereby irrevocably submit.</p>
	<h5><strong>Amended API Terms and Terms</strong></h5>
	<p>We reserve the right to amend these API Terms and Terms at any time without notice to you, but we will use reasonable efforts to publish each amendment before such amendment becomes effective. The latest, fully-amended version of these API Terms and Terms will be published on the Website(s). You are responsible for regularly reviewing the Website(s) to obtain timely notice of such amendments. If any amendment is unacceptable to you, you may terminate the agreement between you and us regarding the use of the Website(s) as set out in these API Terms and Terms. If you continue to use the Website(s) after the effective date of any amendment, you will be conclusively deemed to have accepted such amended version of these API Terms and Terms.</p>
	<h5><strong>UCITA Exclusion</strong></h5>
	<p>Both parties hereby exclude the application of the Uniform Computer Information Transactions Act (“UCITA”), the United Nations Convention on the International Sale of Goods (“CISG”) and any law of any jurisdiction that would apply UCITA or CISG or terms equivalent to UCITA or CISG to these API Terms and Terms. Provisions of these API Terms and Terms that by their nature, or to give effect to their meaning, must survive expiration or termination of these API Terms and Terms, including but not limited to the sections entitled Copyright, Trademark, Disclaimer, Limitation of Liability, Indemnity, Security, and Miscellaneous, shall survive any expiration or termination of these API Terms and Terms.</p>
	<h5><strong>Enforceability</strong></h5>
	<p>If any provision of these API Terms and Terms is held to be invalid, it shall either be (a) reformed only to the extent necessary to make it enforceable, and such decision shall not affect the enforceability (i) of such provision under other circumstances or (ii) of the remaining provisions hereof under all circumstances, or (b) if such reformation is not possible, severed from these API Terms and Terms and the remainder of these API Terms and Terms shall continue in full force and effect. No waiver, amendment, or other modification of these API Terms and Terms, will be effective unless it is in writing signed by Coronavirusapi or posted by Coronavirusapi on this Website.</p>
	<h5><strong>No Waiver</strong></h5>
	<p>No course of conduct shall operate to waive, amend, or modify these API Terms and Terms. The waiver by Coronavirusapi of any of its rights or remedies in a particular instance will not be construed as a waiver of the same or different right or remedy in subsequent instances. Section titles in these API Terms and Terms are for convenience only and shall not be used to limit, extend, or define any provision of these API Terms and Terms.</p>
	<h5><strong>No Injunctive Relief</strong></h5>
	<p>In no event shall you seek or be entitled to rescission, injunctive or other equitable relief, or to enjoin or restrain the operation of the Coronavirusapi API Services or the Coronavirusapi Website, its content or other material used or displayed through the current Coronavirusapi website or successor site.</p>
	<h5><strong>No Third-Party Beneficiaries</strong></h5>
	<p>There are no third-party beneficiaries to this Agreement.</p>
	<h5><strong>Limitation Period</strong></h5>
	<p>Any cause of action you may have with respect to these API Terms and Terms must be commenced within one year after the claim or cause of action arose, or it will be barred.</p>
	<h5><strong>Notices</strong></h5>
	<p>Any notice, consent, waiver, approval, authorization or other communication to be delivered in connection with these API Terms and Terms:</p>
	<ol type="a">
	  <li><p>by us to you will be deemed to have been effectively and validly given if delivered or sent to any of the contact particulars then listed in your account;</p></li>
	  <li><p>by you to us will be deemed to have been effectively and validly given only if in writing and delivered or submitted to [use form].</p></li>
	</ol>
	<h5><strong>Assignment</strong></h5>
	<p>We may at any time assign our rights and obligations under these API Terms and Terms, in whole or in part, without notice to you. You may not assign these API Terms and Terms without our prior, written consent. Any purported assignment and delegation without permission shall be ineffective. These API Terms and Terms will inure to the benefit of and bind you and us and our respective personal and legal representatives, successors and permitted assigns.</p>
	<p> </p>
	<h5><strong>Reservation of Rights</strong></h5>
	<p>All rights not expressly granted herein are reserved by Coronavirusapi. You acknowledge that all intellectual property rights within the Coronavirusapi API Services and within Coronavirusapi remain the property of Coronavirusapi and nothing within these API Terms and Terms will act to transfer any of these intellectual property rights to you.</p>
	<h5><strong>Survival</strong></h5>
	<p>Sections of these API Terms and Terms that, by their terms, require performance after the termination or expiration of these API Terms and Terms will survive.</p>
	<h5><strong>Relationship</strong></h5>
	<p>You agree that no joint venture, partnership, fiduciary, employment, agency or processor-subprocessor relationship exists between us and you as a result of these Terms or use of the Website(s).</p>
	<h5><strong>Force Majeure</strong></h5>
	<p>Neither party will be responsible for a failure to fulfil its obligations under these API Terms and Terms or for delay in doing so if such failure or delay is due to circumstances beyond its reasonable control, such as acts of nature, acts of government, war, riots, strikes and accidents in transportation, pandemic and other similar events, but excluding a lack of financing, cash or credit.</p>
	<h5><strong>Privacy</strong></h5>
	<p>Each of the Website(s) has a Privacy Statement. You acknowledge that you have read the Privacy Statement located on each of the Website(s), as it may be updated from time to time (the &quot;Privacy Statement&quot;).  You further acknowledge that, to the extent required under applicable law, by using such Website you consent to the collection, use, and disclosure by us of your personal information (whether previously collected or to be collected) for the purposes identified therein. You also consent to our use of such personal information in accordance with such Privacy Statement, which is incorporated herein by reference and forms an integral part of these API Terms and Terms.</p>
	<h5><strong>Privacy Policy Updates</strong></h5>
	<p>The Privacy Statement and Terms are current as of the date on the top of this page. We may update the Privacy Terms and Privacy Statement at any time by publishing an updated versions here. If you continue to use the Website(s) after any such changes, that will indicate you accept those changes.</p>
	<h5><strong>Entire Agreement</strong></h5>
	<p>These API Terms and Terms, including the Privacy Policy, as amended from time to time, including any and all documents, Website(s), Content, and/or Coronavirusapi API Services rules, terms and policies referenced herein, constitute the complete and entire agreement between us and you with respect to its subject matter and supersedes all prior agreements, writings or understandings, whether oral or in writing.</p>
	<br>
	<h2><strong>Coronavirusapi Privacy Policy</strong></h2>
	<p><strong>Effective date: February 1, 2020</strong></p>
	<p>Thank you for visiting Coronavirusapi or using Coronavirusapi’s mobile application. Coronavirusapi values its relationship with guests, members, partners, prospects, consultants, consumers, and clients, (collectively “Customers”) and is committed to responsible information handling practices.</p>
	<p>This privacy policy (“Policy”) applies to information collected from you by Coronavirusapi, its subsidiaries and affiliates (collectively “Coronavirusapi”) when you visit websites where this privacy policy is posted, register for information or content Coronavirusapi makes available (“Data”) at our websites, through your download and use of any mobile application, widget, shortcut or user interface (collectively, “Apps”) that Coronavirusapi may make publicly available, and through your electronic communications with Coronavirusapi. This privacy policy also applies to information collected by Coronavirusapi through other means.</p>
	<p>Coronavirusapi’s website and Apps share the following privacy philosophies and principles.</p>
	<ul>
	  <li><blockquote>
	    <p>Providing you with notice of Coronavirusapi's information practices</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Giving you choices about how Coronavirusapi will use information collected from you</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Providing you with the opportunity to update or correct your personally identifiable information</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Using information security safeguards</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Providing you with means to contact Coronavirusapi about privacy-related issues</p>
	  </blockquote></li>
	</ul>
	<p>If you are a resident of California, please refer to the California Privacy Rights section of this Policy.</p>
	<p><strong>Website Terms and Conditions</strong></p>
	<p>Coronavirusapi’s Website Policy as it pertains to web information collected on the Coronavirusapi Website can be found in our Website Terms of Use.</p>
	<p><strong>Table of Contents</strong></p>
	<ol type="1">
	  <li><p>What Information About Me Does Coronavirusapi Collect?</p></li>
	  <li><p>How Does Coronavirusapi Use Information?</p></li>
	  <li><p>Does Coronavirusapi Share of Transfer the Information I Provide?</p></li>
	  <li><p>How Does Coronavirusapi Keep My Personal Information Secure?</p></li>
	  <li><p>Does Coronavirusapi Use Cookies or Other Technologies?</p></li>
	  <li><p>Can Other Parties Obtain Information From Me When I Visit a Coronavirusapi Website?</p></li>
	  <li><p>How Do I Contact Coronavirusapi to Request Access or Correction to my Personally Identifiable Information?</p></li>
	  <li><p>How Do I Opt Out of Receiving Marketing Communications from Coronavirusapi?</p></li>
	  <li><p>Will This Privacy Policy Change?</p></li>
	</ol>
	<p><strong>Privacy Policy Sections</strong></p>
	<p><strong>Section 1: Information Collected</strong></p>
	<p>You may provide Coronavirusapi with two types of information during your visit to Coronavirusapi’s website or your use of our App.</p>
	<ul>
	  <li><blockquote>
	    <p>Information Coronavirusapi collects automatically</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Information that you voluntarily share with Coronavirusapi</p>
	  </blockquote></li>
	</ul>
	<p>The information we collect includes “personal information,” which can have different meanings depending on applicable law. In general, we use the term “personal information” to mean information that can uniquely identify you, but we will treat information we collect from you as personal information wherever necessary under applicable law.</p>
	<p>Coronavirusapi automatically collects information from you when you visit Coronavirusapi’s website or use our App, such as the search engine you used to access the Coronavirusapi website, the previous websites you visited, the websites or advertisements you view or select, the type of browser or device you use, the operating system you use, your computer or device's IP address or other unique identifier, and information about the way you use our App.</p>
	<p>Coronavirusapi may collect the mobile phone number you use to send Coronavirusapi a text message, and the content of the message. When you send a text message to Coronavirusapi, the incoming phone number, the wireless service provider and the date and time of the message will be logged by Coronavirusapi.</p>
	<p>Coronavirusapi may also assign a unique identifying number, code, or both, to the computer or device that you use to visit or access a Coronavirusapi website or App, and Coronavirusapi may collect other information during a particular web browsing session and over time.</p>
	<p>If you use such location-enabled parts of the App or the Coronavirusapi website, you may be sending Coronavirusapi location information. This information may reveal your precise or approximate location.</p>
	<p>Coronavirusapi may also use third-party providers to place and manage Coronavirusapi’s advertisements on the Coronavirusapi website and App. These third parties may use cookies and other technology to automatically collect information on Coronavirusapi’s behalf about your visits to Coronavirusapi websites, use of the Apps and visits to other websites in order to provide advertisements about Coronavirusapi goods and services that may be of interest to you.</p>
	<p>We may ask you to provide personal information when you create an online account, participate in a survey, contact Coronavirusapi with a question or concern, or participate in other activities when you visit a Coronavirusapi website or use the App. If you are a member of social media networks or services, and you authorize Coronavirusapi to associate your account or the App with that network or service, Coronavirusapi will gather information about your online behavior at the Coronavirusapi websites or through your use of the App, will associate that information with personal information Coronavirusapi already has about you and use it on-line or offline, in accordance with this privacy policy. Coronavirusapi also collects personal information that you may disclose on the Coronavirusapi website or through use of the App, such as comments to blogs, and message boards, if any.</p>
	<p>Coronavirusapi retains your personal information for as long as you use the App, or maintain an online account with a Coronavirusapi website, and for a reasonable time thereafter. Coronavirusapi retains anonymous information it collects under this privacy policy for up to two years from the date of collection, and thereafter may only retain such information in the aggregate.</p>
	<p><strong>Section 2: Use of Information </strong></p>
	<p>Coronavirusapi does not sell your personal information. Coronavirusapi uses personal information for the purpose for which you provided it such as to fulfill your request for products, services or Data. Coronavirusapi also uses personal information to notify you of changes to Coronavirusapi’s websites, to let you know about other products and services that may be of interest to you, and to tailor Coronavirusapi's online offerings to your preferences. Coronavirusapi combines anonymous usage information collected from your visit to a Coronavirusapi website or use of our App with that of other users to determine which features and areas of the website or App are most popular. By collecting and analyzing this information, Coronavirusapi can improve the Coronavirusapi websites and App. This aggregated information does not contain information personally associated with you.</p>
	<p>Coronavirusapi may also update and supplement personal information collected from you with other information that Coronavirusapi obtains from third parties or from Coronavirusapi's subsidiaries and affiliates. If Coronavirusapi associates information obtained from affiliates and subsidiaries or other third parties with personal information collected under this policy, Coronavirusapi will treat the acquired information like information Coronavirusapi has collected itself.</p>
	<p>Coronavirusapi uses aggregated data. To the extent this can no longer be considered personal data-for analyzing purposes, for website and internal operations, and for improving the quality of its services. Coronavirusapi uses certain trusted third parties to help us provide, improve and protect our services. These third parties will access your information only to perform tasks on our behalf in compliance with this Policy, and we will remain responsible for their handling of your information so long as they follow our instructions. Coronavirusapi shall not process, transfer, modify, amend or alter personal data to any third party and will not do so without your express consent other than as necessary to provide Services/Support/Licenses of the Customer or as required to comply with Data Protection Laws or other laws to which Coronavirusapi is subject, in which case, Coronavirusapi shall, to the extent permitted by law, inform the Customer of that legal requirement before processing the data.</p>
	<p><strong>Section 3: Sharing Information </strong></p>
	<p>Coronavirusapi may share your information:</p>
	<p><strong>With Coronavirusapi affiliates and subsidiaries.</strong> Coronavirusapi may share your personal information with Coronavirusapi subsidiaries to let you know about Coronavirusapi products and services that may be of interest to you, and other business purposes.</p>
	<p><strong>With Service Providers.</strong> Coronavirusapi may share your personal information with third parties that provide services for Coronavirusapi, such as Data and information requests, to improve your experience with the App and on Coronavirusapi’s website and for other business purposes. Coronavirusapi will share your personal information with these third parties for these purposes; however, these third parties will not contact you directly.</p>
	<p><strong>As Required by Law.</strong> From time to time, Coronavirusapi may be required to share your personal information with law enforcement or other governmental agencies in response to a court order, subpoena, government investigation, or as otherwise required by law. Coronavirusapi also reserves the right to report to law enforcement agencies any activities that Coronavirusapi, in good faith, believes to be unlawful. Coronavirusapi also may share certain personal information when it believes that such sharing is reasonably necessary to protect the rights, property, and safety of others and itself.</p>
	<p><strong>As Part of a Business Transaction.</strong> Coronavirusapi may also disclose your personal information to third parties in relation to planned or potential corporate sales, mergers, reorganizations, consolidations, dissolutions, bankruptcies, or similar events.</p>
	<p><strong>Section 4: Keeping Information Secure</strong></p>
	<p>Keeping Information Secure. We have implemented technical, administrative, and physical security measures designed to protect your personal information from unauthorized access, disclosure, use, and modification. Please be aware that, although Coronavirusapi strives to keep your personal information secure, no security measures are absolute, and Coronavirusapi does not guaranty the security of personal information you provide. Use caution when transmitting personal information over the Internet as you do so at your own risk.</p>
	<p>Any personal data held by Coronavirusapi shall be kept confidential, and Coronavirusapi has implemented protections appropriate to the risk required pursuant to applicable Data Protection Laws and, where the processing concerns of personal data of EU residents, shall take all measures required pursuant to article 32 GDPR and associated implementing laws, revisions and amendments.</p>
	<p><strong>Section 5: Use of Other Technologies</strong></p>
	<p>Use of Other Technologies. The Coronavirusapi website and App may use technology (e.g., cookies, web beacons, and pixel tags) to collect and store information concerning your use of the Coronavirusapi website and App, in order to recognize you, provide personalization, optimize performance of the Coronavirusapi website and App, and collect traffic data (e.g., number of visitors to the Coronavirusapi website, frequency of visits or use, length of visit, and the use made). If you choose to reject all cookies or similar technology, you may be unable to use some of the functionality of the Coronavirusapi website and App.</p>
	<p>The App may also use various technologies to track your web browsing activity conducted through the App and may store such information on your mobile device. Many mobile devices have this technology pre-loaded or incorporated in the web browser, or the technology may be included in a mobile application you download and use on your device. You may be able to manage that information gathering and storage through your device.In some instances, these cookies may be used by us or other web sites during your future navigation of the internet to target specific advertisements to you based on your previous use of the Coronavirusapi website, the App, or other websites.</p>
	<p>The Coronavirusapi website may also read cookies already stored within your browser to identify non-personal information about you and communicate this information to other advertisers. You may remove cookies used by the Coronavirusapi website for advertising purposes by deleting cookies from your browser history. Some browsers have “do not track” features that allow you to tell a website not to track you. These features are not all uniform. We do not currently respond to those signals. Instead, we collect, use, and share information as described in this privacy policy regardless of a “do not track” choice.</p>
	<p><strong>Section 6: Third Party Data Interactions</strong></p>
	<p>Third Party Data Interactions. Coronavirusapi may allow third parties to deliver advertisements on the Coronavirusapi website, through the App or SMS text messages. The Coronavirusapi website and App may also contain links to websites that are owned and operated by third parties. You should be aware that when you click on these third-party advertisements or links, you may deploy technology (such as cookies or web beacons), which third parties may use to identify some of your preferences or to recognize you if you have previously been to their website or otherwise had contact with them. Coronavirusapi has no responsibility (and disclaims any representations, warranties or responsibility) for these third-party advertisements and websites, including, without limitation, their content and privacy policies. Coronavirusapi encourages you to read the privacy policies of the advertisers and websites to learn how they may collect and use information about you. If you voluntarily disclose personal information in a public area of the Coronavirusapi website or App, such as a review page, blog or message board, third parties may collect this information and use it to send you unsolicited marketing communications, messages or for other purposes. You disclose personal information in public areas of the Coronavirusapi website or App at your own risk.</p>
	<p><strong>Section 7: Updating Your Information</strong></p>
	<p>You may correct any errors in your personal information by providing Coronavirusapi with the correct information by sending an email to <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a> with an explanation of your specific request. In jurisdictions where your consent is required at the point of collection before any sharing of your information can take place, you will be notified at the collection point that your information will be shared, and submission of your contact information will be confirmation of your consent to opt-in for the transfer of your contact information to the referenced third party. </p>
	<p>You have the “right to be forgotten” (the right for your information to be deleted). You may uninstall the App from your mobile device at any time, and Coronavirusapi will make reasonable efforts to delete the personal information in its possession concerning your use of the App; however, you will continue to receive e-mail, SMS text messages and other communications if you selected those services through your account at the Coronavirusapi website. Coronavirusapi will delete all of your personal information (except for your transaction history) from Coronavirusapi records upon your written request. However, you will not be able to access some areas of the Coronavirusapi website, use some aspects of the App or have the App function properly if you choose to delete your personal information. Contact Information: <strong>Coronavirusapi Attn: Privacy Manager, 7 Lawridge Drive, Rye Brook, NY 10573</strong></p>
	<p><strong>Section 8: Opt Out</strong></p>
	<p>Opt Out. You may also opt out of receiving communications from Coronavirusapi by following the directions in Coronavirusapi by e-mailing <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a> or by mailing your request, which must include your current contact information, to <strong>Coronavirusapi Attn: Privacy Manager, 7 Lawridge Drive, Rye Brook, NY 10573.</strong></p>
	<p>You may stop the delivery of Push Notification or other e-mail messages from Coronavirusapi by managing your notification preferences in the account settings section of the App or your online account with an Coronavirusapi website. Coronavirusapi will implement your request within a reasonable time. Please note that your request to opt out of receiving marketing communications will only apply to future communications and transactions with Coronavirusapi and its service providers. Even if you choose to opt out of receiving marketing communications from Coronavirusapi, Coronavirusapi will still send you transactional or administrative communications. States have varying laws about privacy which may require specific privacy policies to be provided, and so, will only apply to you provided you live in such a jurisdiction.</p>
	<p>If you have questions, please contact <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a>.</p>
	<p><strong>Section 8: Policy Changes</strong></p>
	<p>Policy Changes. Coronavirusapi may change this privacy policy at any time. If Coronavirusapi modifies this privacy policy, Coronavirusapi will post it on the Coronavirusapi website and the App and include the effective date of the modification. If there are material changes to this privacy policy, Coronavirusapi may notify you of the modification by sending you an e-mail at the last e-mail address you provided to us, posting a notice through the App, by prominently posting notice of the modification here and on the home page for each Coronavirusapi website governed by this privacy policy, through other reasonable delivery methods, or as otherwise required by law. Coronavirusapi shall not be responsible for the acts of those who gain unauthorized access, and my not provide prior notice to you of any policy updates.</p>
	<p>Your use of the Coronavirusapi website or App means that you accept the terms of this privacy policy and that Coronavirusapi has the right to use information it collects from you, whether personal information or anonymous, as stated in this privacy policy. If you do not accept the terms of this privacy policy, do not use the Coronavirusapi website or App. If you have any additional questions, please feel free to contact Coronavirusapi any time at <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a></p>
	<p><strong>California Privacy Rights Specific Sections:</strong></p>
	<p>We collect information that identifies, relates to, describes, references, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular California consumer or household (“personal information”).</p>
	<p>California Civil Code Section 1798.83 permits California residents to request certain information regarding Coronavirusapi’s disclosure of personal information to third parties for their direct marketing purposes. To request such information, please contact us through the “Contact” section. Please be advised that in certain instances, it may be required for Coronavirusapi to disclose your personal information to a governmental body by law for example under a subpoena, warrant or court-issued request for information. For additional information, see <strong>Policy Section 1</strong> that describes what information we collect about you. </p>
	<p>We may use the personal information we collect for our operational purposes or other purposes set out in this privacy policy. Those purposes may include:</p>
	<ul>
	  <li><blockquote>
	    <p>Auditing related to a current interaction with the website user and concurrent transactions, including, but not limited to, counting ad impressions to unique visitors, verifying positioning and quality of ad impressions, and auditing compliance with this specification and other standards.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Detecting and monitoring security events, protecting against malicious, deceptive, fraudulent, or illegal activity, and prosecuting those responsible for that activity.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Debugging to identify and repair errors that impair existing intended functionality.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Short-term, transient use, provided the personal information that is not disclosed to another third party and is not used to build a profile about a User or otherwise alter an individual consumer’s experience outside the current interaction, including, but not limited to, the contextual customization of ads shown as part of the same interaction.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Performing services on behalf of the business, including maintaining or servicing accounts, modifying loyalty program services, providing customer service, processing or fulfilling orders and transactions, verifying customer information, processing payments, providing advertising or marketing services, providing analytic services, or providing similar services on behalf of the business.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Undertaking internal research for technological development and demonstration.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Undertaking activities to verify or maintain the quality or safety of a service that is owned, manufactured, manufactured for, or controlled by the business, and to improve, upgrade, or enhance the service that is owned, manufactured, manufactured for, or controlled by the business.</p>
	  </blockquote></li>
	</ul>
	<p>We also use the personal information we collect for our commercial or economic purposes, such as attracting consumers to join, subscribe to, provide, or exchange information, or services, or enabling or effecting, directly or indirectly, a commercial transaction.</p>
	<p>For additional information, see the <strong>Policy Section 2</strong> that describes how we use the information about you.  <strong>third parties with whom we share personal information</strong></p>
	<p>For information on where we share personal information, see the <strong>Policy Section 3</strong> describing sharing information.</p>
	<p>You have the right to ask us to send you the following information:</p>
	<ol type="1">
	  <li><blockquote>
	    <p>The categories of personal information we have collected about you.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>The categories of sources from which we collected the personal information.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>Our business or commercial purpose for collecting personal information.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>The categories of third parties with whom we share personal information.</p>
	  </blockquote></li>
	  <li><blockquote>
	    <p>The specific pieces of personal information the business has collected about you.</p>
	  </blockquote></li>
	</ol>
	<p>You have the right to ask us to delete the personal information about you we have collected.</p>
	<p>Your privacy rights are important. If you exercise your privacy rights under California law, we will not do any of the following in retaliation:</p>
	<ol type="1">
	  <li><p>Deny you goods or services.</p></li>
	  <li><p>Charge you different prices or rates for goods or services, including through the use of discounts or other benefits, or imposing penalties.</p></li>
	  <li><p>Provide you a different level or quality of goods or services.</p></li>
	  <li><p>Suggest that you may receive a different price or rate for goods or services or a different level or quality of goods or services. <strong>residents can submit requests</strong></p></li>
	</ol>
	<p>If you are a California resident and you want to submit a request to us regarding your California rights, you can contact us via e-mail to <a href="mailto:sjoseph@susangjoseph.com">sjoseph@susangjoseph.com</a>. You do not have to create an account with us to submit a request.</p>
	<p>We can only respond to your request if it is verifiable. This means we are obligated to take reasonable steps to verify your identity and your right to access the information you request. We may ask you to provide additional information that will help us do so. We will only use that additional information in the verification process, and not for any other purpose.</p>
	<p>We do not charge a fee to process or respond to your verifiable consumer request unless it is excessive, repetitive, or manifestly unfounded. If we determine that the request warrants a fee, we will tell you why we made that decision and provide you with a cost estimate before completing your request.</p>


</section>







